name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        emacs_version:
        - 25.1
        # 25.2 is identical to 25.3 except for a critical security bug in
        # enriched text mode (see Emacs Bug#28350).
        - 25.3
        - 26.1   # Debian is on this version.
        - 26.3
        - 27.1
        - snapshot
        git_impl:
        - git
        # FIXME Broken due to glibc version mismatch. See #4456.
        # - libgit
    steps:
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: emacs-ci
    - uses: actions/checkout@v2
    - name: Install
      run: |
        # Build and install Emacs (+ magit dependencies) using Nix
        emacs_ci_version=$(echo "emacs-${{ matrix.emacs_version }}" | sed -e "s/\./-/g")
        nix-env -f ./t/default.nix -iA $emacs_ci_version
        emacs --version

        # Configure Git
        git config --global user.name "A U Thor"
        git config --global user.email a.u.thor@example.com
        git tag 0
    - name: Test
      run: |
        make test-${{ matrix.git_impl }} DASH_DIR=$PWD
