;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(c-electric-slash
                               c-electric-colon
                               cua-delete-region
                               forward-sexp
                               backward-sexp
                               smart-tab
                               my-forward-word-or-buffer-or-windows
                               cua-paste-pop
                               cua-paste
                               cua-cut-region
                               c-electric-delete-forward
                               c-electric-paren
                               c-electric-semi&comma
                               my-backward-word-or-buffer-or-windows
                               kill-region
                               end-of-buffer
                               my-beginning-of-line-or-indentation
                               minibuffer-complete-and-exit
                               forward-paragraph))

(setq mc/cmds-to-run-once '(c-electric-backspace
                            cua-scroll-up))
